Add files via upload
qbcore-framework/qb-houses pull request #140
Opened 2022-01-19 16:36 UTC by netlork

es.lua
Spanish translation.
Traducción al español.

2022-01-19 16:45 UTC, MonkeyWhisper requested changes
Hola, gracias por la traducción.. pero hay que cambiar a couple of things... they sound a bit weird.

2022-01-19 16:49 UTC, MonkeyWhisper commented
["realestate_only"] = "Solo la inmobiliaria puede usar este comando",
This should read something like "Solo bienes raíces suede vender casas" 

["failed_invasion"] = "No se pudo intentar de nuevo",
La invasion de la policia fallo or something along those lines

["open_stash"] = "Abrir armario",

["stash"] = "Armario",

And for these two... armario? I'm not sure. Can we find another word for it? Maybe reservas or inventario privado?

2022-01-19 16:56 UTC, netlork commented
ok, i check it. I'll try to match more with the context.

2022-01-19 17:02 UTC, MonkeyWhisper commented
> ok, i check it. I'll try to match more with the context.

Yeah exactly! Okay, you understand where I'm going with it, awesome.

2022-01-19 17:22 UTC, netlork commented
Changed. 
My only doubt is with "failed_invasion", if I'm not mistaken, is failing an attempt to force the door?

2022-01-19 18:43 UTC, MonkeyWhisper requested changes

2022-01-19 18:43 UTC, MonkeyWhisper commented on locales/es.lua
> +        ["realestate_only"] = "Solo la inmobiliaria puede vender casas",
Change the word inmobiliaria to bienes raíces - this is a more commonly known Spanish over.

2022-01-19 18:43 UTC, MonkeyWhisper commented on locales/es.lua
> +        ["open_stash"] = "Abrir alijo",
That's not a known universally known Spanish word

2022-01-19 18:44 UTC, MonkeyWhisper commented
> Changed.
> My only doubt is with "failed_invasion", if I'm not mistaken, is failing an attempt to force the door?

Yes when the police is trying to battery ram the house

2022-01-20 08:09 UTC, netlork commented on locales/es.lua
> +        ["realestate_only"] = "Solo la inmobiliaria puede vender casas",
I'm sorry, but "bienes raíces" is not a common word (although it exists), the correct word is "inmobiliaria" (a business that sells houses, garages, etc).
I'm from Spain and Spanish is my native language :P

But if you consider that it is better to use "bienes raíces" I have no problem.  :)

2022-01-20 08:15 UTC, netlork commented on locales/es.lua
> +        ["open_stash"] = "Abrir alijo",
I can change it for "escondite" or "escondrijo", a secret and safely storage.

2022-01-20 14:27 UTC, MonkeyWhisper commented on locales/es.lua
> +        ["open_stash"] = "Abrir alijo",
Where are you from? Seems like those are words from European Spanish.

I'm fine with Escondite yes, thanks

2022-01-20 14:43 UTC, netlork commented on locales/es.lua
> +        ["open_stash"] = "Abrir alijo",
> Where are you from? Seems like those are words from European Spanish.
> 
> I'm fine with Escondite yes, thanks

I'm from Spain :)   So yes, those are European Spanish words.
I'll try to use language known as "neutral spanish". :)

2022-01-21 03:03 UTC, jay-fivem requested changes
Can you please add the new locales from #141

2022-01-21 05:34 UTC, MonkeyWhisper commented on locales/es.lua
> +        ["realestate_only"] = "Solo la inmobiliaria puede vender casas",
It is bienes raices, no one know what a inmobiliaria is... lol Let's use that and I'll approve this RP 

Thank you for working with me on this

2022-01-21 05:35 UTC, MonkeyWhisper commented on locales/es.lua
> +        ["open_stash"] = "Abrir alijo",
Okay, that's good! Escondite works

2022-01-21 05:36 UTC, MonkeyWhisper commented
> 

Of course my boi! We got you.

2022-01-21 07:18 UTC, jacanales commented on locales/es.lua
> +        ["realestate_only"] = "Solo la inmobiliaria puede vender casas",
I also think "inmobiliaria" is the world use un standard spanish. "Bienes raíces" is the think that is sold, when we're talking about t'he company which sells those "bienes raíces"

2022-01-21 07:25 UTC, jacanales approved these changes

2022-01-21 07:55 UTC, netlork commented on locales/es.lua
> +        ["realestate_only"] = "Solo la inmobiliaria puede vender casas",
> It is bienes raices, no one know what a inmobiliaria is... lol Let's use that and I'll approve this RP
> 
> Thank you for working with me on this.
> 
> I'm Cuban so Spanish is also my native language

Ok, it's already changed.
Although I think it's still wrong, it's not the usual way of using it and it sounds "weird".
But the important thing is that the translation is available and understandable for everyone :)

2022-01-21 14:35 UTC, MonkeyWhisper approved these changes
Approved, thanks.

2022-01-21 14:36 UTC, MonkeyWhisper commented
Thank you for the corrections!

2022-01-21 14:41 UTC, netlork commented
> Thank you for the corrections!

Thanks to you.
I'll try to translate more modules.

2022-01-22 15:08 UTC, merged