Update pt.lua
qbcore-framework/qb-houses pull request #207
Opened 2022-08-31 13:58 UTC by catiagomes94a

**Describe Pull request**
Missing phrases on translate of portuguese (pt) so i decided fix this.

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes]
- Does your code fit the style guidelines? [yes]
- Does your PR fit the contribution guidelines? [yes]

2022-08-31 14:00 UTC, D4isDAVID requested changes

2022-08-31 14:00 UTC, D4isDAVID commented on locales/pt.lua
> +        ["enter_unlocked_house"] = "Entrar na casa,
```suggestion
        ["enter_unlocked_house"] = "Entrar na casa",
```
Finish the string here

2022-08-31 14:04 UTC, catiagomes94a commented on locales/pt.lua
> +        ["enter_unlocked_house"] = "Entrar na casa,
ty

2022-09-06 06:52 UTC, D4isDAVID approved these changes
LGTM

2023-06-26 19:51 UTC, rodrigoandrade1 commented
Fix realestate_only translation please

2023-09-17 09:07 UTC, merged